apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'prod'

          name: gateway-service
          image: niesuv/gateway-service:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              name: internal-port
      restartPolicy: Always
      