apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      name: config-server
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: niesuv/config-server:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
              protocol: TCP
              name: internal-port

      restartPolicy: Always
      