apiVersion: v1
kind: Service
metadata:
  name: gateway-service-pub
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: internal-port
  type: LoadBalancer
  