apiVersion: v1
kind: Service
metadata:
  name: config-server-vpc
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: internal-port
  type: ClusterIP
  