apiVersion: v1
kind: Service
metadata:
  name: user-service-vpc
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: internal-port
  type: ClusterIP
  