
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: sang
    volumes:
      - mysql-vol:/var/lib/mysql
    networks:
      - my-net
    ports:
      - "3306:3306"


volumes:
  mysql-vol:
    driver: local



networks:
  my-net:
    driver: bridge