version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sang
    volumes:
      - mysql-vol:/var/lib/mysql\
    networks:
      - my-net
    ports:
      - "3306:3306"


volumes:
  mysql-vol:

networks:
  my-net:
    driver: bridge