spring:
  application:
    name: s3-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: optional:configserver:http://localhost:8001

server:
  port: 8004




