server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://${backend_server}:3306/facebook_post
    username: "${mysql_user}"
    password: "${mysql_password}"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB