server:
  port: 80


current_profile: prod

spring:
  datasource:
    url: 'jdbc:mysql://${backend_server}:3306/facebook_user'
    username: "${mysql_user}"
    password: "${mysql_password}"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect