spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configs
            - classpath:/configs/{application}
            - classpath:/configs/{application}-{profile}
  main:
    banner-mode: off

server:
  port: 8001



#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8002/eureka/
logging:
  level:
    web: warn

