spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8001


  datasource:
    url: jdbc:mysql://localhost:3306/facebook_user
    username: root
    password: sang
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

