spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8001


  datasource:
    url: jdbc:mysql://localhost:3306/facebook
    username: root
    password: sang

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8003
