spring:
  application:
    name: gateway-service

  config:
    import: configserver:http://config-server-vpc

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8003
          predicates:
            - Path=/api/v1/user/**

        - id: post-service
          uri: http://localhost:8005
          predicates:
            - Path=/api/v1/post/**

        - id: s3-service
          uri: http://localhost:8004
          predicates:
            - Path=/api/v1/s3/**


